### ISSUE TITLE
com.valvesoftware.unity.openvr-1.2.1.tgz missing meta files

### ISSUE THREAD

**Issue by kfird214** [ValveSoftware/steamvr_unity_plugin#1107]
The zip file for the package `com.valvesoftware.unity.openvr-1.2.1` included with the unity package is missing 2 meta files for:

- _package\Runtime\x86\libopenvr_api.so.meta_
- _package\Runtime\x86\libopenvr_api.so.dbg.meta_

```
Unhandled log message: '[Error] Asset Packages/com.valvesoftware.unity.openvr/Runtime/x86/libopenvr_api.so has no meta file, but it's in an immutable folder. The asset will be ignored.'. Use UnityEngine.TestTools.LogAssert.Expect
```

### My workaround

- Unzipped the zip
- Let Unity create the meta files
- Discarded any other changes Unity made but those meta files (easy when using git)
- Reziped the package as tgz

**Comment by muraqqi** [comment]
hi, i encounterd the same error. some questions about your workaround?
1. the zip file is the master zip from this github page?
2. and then copy the content to my project folder?
3. do i need to delete the steamvr folder or just overwrite the files?
4. what packaged need to rezipped as tgz?

thank you for helping.

**Comment by kfird214** [comment]
> hi, i encounterd the same error. some questions about your workaround?
> 
> 1. the zip file is the master zip from this github page?
> 2. and then copy the content to my project folder?
> 3. do i need to delete the steamvr folder or just overwrite the files?
> 4. what packaged need to rezipped as tgz?
> 
> thank you for helping.

1. If you use the .unitypackage from [2.8.0 release](https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.8.0)
    You will see that there is a file `com.valvesoftware.unity.openvr-1.2.1.tgz` that is added to the packages on `Packages/manifest.json`
    ```json
    "com.valvesoftware.unity.openvr": "file:../Assets/SteamVR/OpenVRUnityXRPackage/Editor/com.valvesoftware.unity.openvr-1.2.1.tgz",
    ```
    This zip file is a unity package itself and inside of it `package\Runtime\x86\libopenvr_api.so` is without a metafile.
    I just unzipped it added a meta file for those 2 files zipped it as tar file with 7z and then gzipped the tar with 7z and renamed it to `.tgz`
    
   2. No need to have any change but the `com.valvesoftware.unity.openvr-1.2.1.tgz` itself.
  
  3. No need to delete anything
  
  4. Your local extracted content of `com.valvesoftware.unity.openvr-1.2.1.tgz`  that has the meta files added manually.

**Comment by PixelDrennen** [comment]
I'm confused why this is still an issue

**Comment by irmakoz1** [comment]
I have the same problem. No meta files in the folder x86 for windows. How can I generate this files?

**Comment by kfird214** [comment]
> I have the same problem. No meta files in the folder x86 for Windows. How can I generate these files?

You can see my answer above https://github.com/ValveSoftware/steamvr_unity_plugin/issues/1107#issuecomment-1909835386

Basically, I unpacked the package, opened it in Unity, and let it generate the file. and re-zipped the package.

**Comment by irmakoz1** [comment]
I already unpacked and opened in unity but how do you regenerate the files?

**Comment by kfird214** [comment]
> I already unpacked and opened in unity but how do you regenerate the files?

Unity should generate the file for you if you open it in a project, I use git to see the diff, it helped me locate the file if I remember correctly.

just packed the same unpacked folder back to a tar file or something and replaced it, and it worked

**Comment by kfird214** [comment]
![explorer_1NXmCcO0sB](https://github.com/ValveSoftware/steamvr_unity_plugin/assets/25746948/be366744-6566-409b-b25e-4e81f4d90d33)

This is the libopenvr_api.so.meta link https://www.dropbox.com/scl/fi/tbiyf90rje96yibqr14tz/libopenvr_api.so.meta?rlkey=a63artnplm8qhbcf6y7cwhd0r&dl=0

Add it to the right path (of course unzip then re-zip)

Here is my com.valvesoftware.unity.openvr-1.2.1.tgz  https://www.dropbox.com/scl/fi/ylbudx4cjgxfs9rc41f9z/com.valvesoftware.unity.openvr-1.2.1.tgz?rlkey=susbp2f7wkincav5rea2aposf&dl=0

> For me unity gives error : no meta files for the files mentioned above and does not regenerate them😕 Even after I unzip and open in the project. Thank you for your response

**Comment by HilaryDeBlick** [comment]
For anyone not wanting to go through the hassle of unpacking, generating the missing meta files and repacking. Here is the zipped tar. Just unzip and overwrite the previous tar file with this one at ..\Assets\SteamVR\OpenVRUnityXRPackage\Editor and it should be fixed.
[com.valvesoftware.unity.openvr-1.2.1.zip](https://github.com/user-attachments/files/16814475/com.valvesoftware.unity.openvr-1.2.1.zip)

**Comment by AdamBebko** [comment]
@HilaryDeBlick 's fix worked for me.

**Comment by ZanyFG** [comment]
it's honestly abysmal, unacceptable even, that it's been _nearly a year and a half_ since release 2.8.0 and this issue still hasn't been fixed.

i did a quick test where i created two new Unity 6000.0.43f1 projects. in one project i imported the .unitypackage from the github releases, and the other i installed the plugin via the asset store. both still had the issue.

unrelated issue, but i discovered that the version number in the readme for the .unitypackage is still v2.7.3 (sdk 1.14.15) which is incorrect, but it's fixed on the asset store version?

i don't know what's going here, but it seems like Valve is just wasting developer's valuable time for absolutely no reason. you would think that if they wanted developers to support their platform then they would give them better support and not put them on a wild goose chase fixing an issue for them because they forgot to include 2 files in their release.

**Comment by OrangyTang** [comment]
A variant of this bug exists in the latest beta release (v2.8.5):

> A meta data file (.meta) exists but its asset 'Packages/com.valvesoftware.unity.openvr/Runtime/x64/XRSDKOpenVR.pdb' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.
> Couldn't delete Packages/com.valvesoftware.unity.openvr/Runtime/x64/XRSDKOpenVR.pdb.meta because it's in an immutable folder.

If you want to fix it locally, extracting the archive, removing the file and repacking the archive as above will work.
