### ISSUE TITLE
Error with URP Camera Stacking

### ISSUE THREAD

**Issue by djlins** [ValveSoftware/steamvr_unity_plugin#753]
Hi there,
I have tried a few tests to confirm there is an issue before I just post, but to highlight how to reproduce it:

I have installed the latest unity (2019.4.0) and then started a new URP project. Then imported the SteamVR unity asset.

Then I opened the demo scene -
\\Assets\SteamVR\InteractionSystem\Samples\Interactions_Samples.unity
So it is the base steamvr sample scene for unity.
I Upgrade the materials to stop them all being pink and run it thorugh the Vive headset.
All is good, if I run it, I can mess about in the world in my headset.

I now introduce a cube and give it a new custom layer (TestOverlayCamera)
I introduce a new camera and set the culling to be only "TestOverlayCamera" and set it to be an OVERLAY camera
I set the original SteamVR camera culling to be everything but TestOverlayCamera
again all is good, I cannot see the cube.

I add the overlay camera to the VRbase camera's stack

I still cant see the cube, but I can see it on the camera view on my editor window.

It seems that the headset renders ignore any overlay cameras in the base cameras stack.

To further prove that I think this might be a bug in the SteamVR camera it is definitely only the SteamVR headset camera that has these issues. If I unplug the headset so that it forces the demo scene to play through the game panel through the FallbackObjects Camera then it does show the cube on the overlay camera rendered over the primary camera in the stack.

So it is a fundamental difference with just the SteamVRObjects\VRCamera and the camera on NoSteamVRFallbackObjects\FallbackObjects

I think that it is pointing towards a bug then with the SteamVR. 
Does this sound sane heheh or am I missinga  fundamental setting for making an overlay camera for the base   SteamVRObjects\VRCamera

Thanks in advance,

Lindsay.

**Comment by fgheorghe** [comment]
👍 having the same issue - any clues?

**Comment by djlins** [comment]
Hi there,
It seems that URP camera stacking didn't work in Unity 2019 (at least not very well)
They claim to be introducing it properly in Unity 2020. See point 2 here for the announcement:
http://www.cgchannel.com/2020/07/discover-5-key-features-for-cg-artists-in-unity-2020-1/
If you are doing a production release of something then they still recommend using Unity 2019 but depending on how important camera stacking is to your project you might want to gamble on a production release using 2020?

**Comment by fgheorghe** [comment]
Thank you for your reply.

Indeed:
"In the initial implementation, Camera Stacking is not supported by the 2D Renderer or the VR Multi Pass mode: something that Unity Technologies says will be added in “upcoming versions” of the URP."

So I am assuming in 2020 they are introducing multipass rendering, but no mentioning of a fix for camera stacking in VR. 
Will give 2020 a try, but last time I tried VR in 2020 it was quite slow and more buggy than Unity's usual flakiness. 

If I find anything I will keep you posted - this bug is annoying as camera stacking is indeed quite useful.

**Comment by djlins** [comment]
Thanks for that, yes I agree that camera stacking would help with a lot of things for me visually.

**Comment by fgheorghe** [comment]
Interesting - if I disable post processing on the main camera, the issue is gone. So it could be an issue with either PP or OpenVR?

**Comment by djlins** [comment]
URP camera stacking issues with VR and should be fixed in later iterations of Unity 2020 onwards

**Comment by blasco** [comment]
I cannot make camera stacking to work in VR. Is this still not working?

**Comment by djlins** [comment]
Hiya, I actually gave up on it because it didn't work in Unity 2019.

If you do manage to get it working on Unity 2020 would you mind letting me know?

Cheers,

Lins.

**Comment by fgheorghe** [comment]
For my use case, the above workaround works: ensuring that post processing is only enabled for the top stacked camera (the last camera to render). Works for both eyes.

**Comment by LukasSDCVentures** [comment]
Camera stacking does still not work in unity 2021.3. It looks like theres also still a Problem with enabling post processing since the Game won't lounch if enabled. I am working with the oculus quest 2. Any Progress with this? @blasco

**Comment by djlins** [comment]
Hi Lukas,
I'm afraid not. I no longer try to use post processing or Camera Stacking unless I am tethered to a PC GPU.
I'm also using 2021.3.3f1 for normal Quest development and keep it very basic because I think you just have to streamline your draw calls and shave it right down to the bare minimum.
I was using Vulkan for a while on Unity 2019 but even that now seems to be broken again in Unity 2021 so I am back to OpenGLES3 for Quest development.
