### ISSUE TITLE
VR hands flipped and rotated

### ISSUE THREAD

**Issue by josh-65** [ValveSoftware/steamvr_unity_plugin#964]
**Issue**
The hands are rotated (in the screenshot my controllers are facing up) They are also flipped (fixed by making hand models opersit). I'm using a Oculus quest 1 in rift mode with the link cable

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/123097354-fe49e200-d427-11eb-8cd7-b0fbbee77eb1.png)

**Versions**
SteamVR: 1.18.3 beta
Unity: 2020.3.1f1
SteamVR plugin: 2.7.3 (SDK 1.14.15)

**Comment by zite** [comment]
Can you reproduce the same behavior in a new project having just imported the plugin and running the interaction system example scene?

**Comment by KellanHiggins** [comment]
Look at my prior posts in this repo. I figured this out like 2 years ago (but forgot what I did to fix it). I think I set the origin to something else and then it caused all sorts of weird behavior.

**Comment by Josh65-2201** [comment]
@keithbradner  I cant get it to install on a new build as it say i could not install OpenVR
![image](https://user-images.githubusercontent.com/26977075/123520679-b3d79800-d6a9-11eb-9259-381c8a960421.png)

**Comment by josh-65** [comment]
@KellanHiggins I cant find any posts that have this issue on here

**Comment by KellanHiggins** [comment]
I think this may be related. The hands were coming in weird posts and reversed. Had something to do with assigning the wrong core.

https://github.com/ValveSoftware/steamvr_unity_plugin/issues/514

**Comment by josh-65** [comment]
thanks il try this

**Comment by josh-65** [comment]
>  I had modified the root / wrist on the pose that I had created

@KellanHiggins I don't know were/what this is referring too.

**Comment by KellanHiggins** [comment]
Honestly, no idea as well. It has been a very long time since I looked at this. It also may have been fixed.

**Comment by keithbradner** [comment]
> @keithbradner I cant get it to install on a new build as it say i could not install OpenVR
> ![image](https://user-images.githubusercontent.com/26977075/123520679-b3d79800-d6a9-11eb-9259-381c8a960421.png)

This looks to be a problem on your system. Can you try creating an entirely new project, and installing the steamvr unity plugin from the asset store?

**Comment by josh-65** [comment]
That's what I did

**Comment by zite** [comment]
Hmm, I'll try to reproduce that on my end. Still the same unity version? 2020.3.1?

**Comment by josh-65** [comment]
yes

**Comment by zite** [comment]
Can you try upgrading your version of unity? Looks like they're up to 2020.3.12f1. Seems like it may be a unity issue

**Comment by josh-65** [comment]
ok il try that

**Comment by josh-65** [comment]
i updated to version 13 and installing worked. ill try see if the hands are flipped later.

**Comment by josh-65** [comment]
The hands are correctly placed in a new project but in my one there are still flipped. I try using the player prefab I already had and a new one both with the same result.

**Comment by josh-65** [comment]
I recently implemented a full player modal that allows me to change hand rotation offsets so this is not an issue I have to deal with anymore.
